---
title: "What makes a popular Reddit post?"
author: "InterstellR"
date: "May 2, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

"Reddit is an American social news aggregation, web content rating, and discussion website" (from [wikipedia](https://en.wikipedia.org/wiki/Reddit)). People who are members of Reddit upload their posts and other people vote and comment on said posts, the posts with the most likes appear more towards the top. They are divided by thematic categories called subreddits, as well as overall categories of top posts, new posts, controversial posts, among others. 

### Data Set
The data set is comprised of Reddit posts from December 2017, since it was the latest data set we could find and wanted to keep up with the most recent trends. Also,  it will be interesting to explore themes related to Christmas. We retrieved it from the google BigQuerry API. The data set contains .. variables and .. observations. 

### Research Questions



## Conclusion
